blank_issues_enabled: false
contact_links:
  - name: ğŸ™ğŸ» Support This Project
    url: https://github.com/sponsors/tallguyjenks
    about: Help support continued development on this project
  - name: ğŸ‘¨ğŸ»â€ğŸ’» More about the maintainer
    url: https://www.bryanjenks.dev/
    about: get to know the maintainer of PyRM
